# permissions for end users to view supervisorspecs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: supervisorspec-viewer-role
rules:
- apiGroups:
  - druid.apache.org
  resources:
  - supervisorspecs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - druid.apache.org
  resources:
  - supervisorspecs/status
  verbs:
  - get
